### ISSUE TITLE
Unable to update to latest 1.0.3

### ISSUE THREAD

**Issue by oviliz** [shipperhq/module-shipping-tracker#12]
Hi @wsajosh , as a follow up to https://github.com/shipperhq/module-shipping-tracker/issues/8, shouldn't be possible to do `composer update shipperhq/module-shipping-tracker`?
```
$ composer update shipperhq/module-shipping-tracker
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
...
```
It seems that I'm unable to update for some reason.
```
$ composer show  | grep shipperhq
shipperhq/module-shipping-tracker                 1.0.1     Shipping Tracker - By the ShipperHQ Team
```
```
$ cat composer.json | grep shipperhq
        "shipperhq/module-shipping-tracker": "^1.0",
```
Any thoughts?

I've even tried to amend composer.json to say ^1.0.3 but does not want to hear:
```
$ composer update shipperhq/module-shipping-tracker:1.0.3
Package "shipperhq/module-shipping-tracker:1.0.3" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
```

Perhaps because of this line?
https://github.com/shipperhq/module-shipping-tracker/blob/47380d5d18f12aafd7487640b2a47e88997b621a/composer.json#L11

**Comment by ibraheemnabeelfauzi** [comment]
Hey there @oviliz  we're looking into this and we'll get back to you with more details very soon. 

Cheers.

**Comment by ibraheemnabeelfauzi** [comment]
@oviliz 

You should be able to update now - please follow the instructions here, latest release is 1.0.4: http://support.webshopapps.com/shippingtracker/installing-the-magento-2-webshopapps-tracker-extension/

**Comment by oviliz** [comment]
Thank you very much. This did it and I finally have the fix to all trackings being sent to customers.
