### ISSUE TITLE
DPD UK Tracking

### ISSUE THREAD

**Issue by drinkingsouls** [shipperhq/module-shipping-tracker#15]
Hi ShipperHQ
We're using version 1.0.4 with Magento 2.4.4-p2.
In shipment emails the tracking number used to link to DPD correctly with the number flled but now it redirects to the track.dpd.co.uk page without the tracking number in. I assume the DPD link has changed and it is not updated? The tracking url in TrackingNumbers.pdf is the same as the url set in our emails.
The Royal Mail UK link still works as expected.
Thank you,
Chris

**Comment by wsadaniel** [comment]
Hi @drinkingsouls we'd responded to this via email but wanted to post here as well:
It appears that DPD has altered the way its tracking webpage functions. It now redirects to the [track.dpd.co.uk](http://track.dpd.co.uk/) URL.

`https://www.dpdgroup.com/nl/mydpd/my-parcels/track?lang=en&parcelNumber=#TRACKNUM#`

`https://www.dpdlocal-online.co.uk/tracking/#TRACKNUM#`

Our placeholder for customers is `#TRACKNUM#`, if you append this to the URL you're using this should solve the issue.

**Comment by drinkingsouls** [comment]
Hi,

Neither of the above links work either. It seems an extra set of digits are appended after tracking numbers now which makes it more tricky.

For example, to track a parcel of mine. 15976834252345 is the tracking number. It then appends *20109 to the link after that.
I do not know what those extra digits represent but they are not the same twice.

![track](https://user-images.githubusercontent.com/45666862/219417296-09f12c06-0c61-4074-ab52-89b949e0e3ca.jpg)

I have tried to contact DPD but every email I send bounces, social media support is ignored and contact forms don't work.

Thank you.

**Comment by drinkingsouls** [comment]
Here is another example of this with a different parcel.

![track](https://user-images.githubusercontent.com/45666862/219418575-17c5d02b-081b-4f70-aa66-7fde344b20bc.jpg)

**Comment by drinkingsouls** [comment]
Another example of this with a different parcel.

![track3](https://user-images.githubusercontent.com/45666862/219419946-1cb4c789-85ae-48df-ad2a-08d8d34d0fc6.jpg)

**Comment by wsadaniel** [comment]
Thanks for the feedback @drinkingsouls . We are planning on updating the extension to account for the change in DPD URLs and we'll review that URL as part of that.
