### ISSUE TITLE
Extension Version

### ISSUE THREAD

**Issue by ginoigroup** [shipperhq/module-shipping-tracker#16]
Hello,

Just to inform that latest version v1.0.6 is available at  https://commercemarketplace.adobe.com/shipperhq-module-shipping-tracker.html.

Thanks,
Daniel

**Comment by WSAlewis** [comment]
Hello @ginoigroup, thanks for raising this.

I'm reaching out to our team to review this version discrepancy and update accordingly.

If you have any questions or concerns here, let us know.
